name: Release to dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    uses: cere-io/reusable-workflows/.github/workflows/deploy-to-cloudfront.yaml@master
    with:
      build_container: 'node:18-buster-slim'
      install_packages_command: 'cp .env.dev .env; npm ci'
      build_command: 'npm run build'
      path_to_static_files_to_upload: 'build'
      aws_account_id: ${{ vars.DEV_CORE_AWS_ACCOUNT_ID }}
      s3_bucket_name: 'qr-code-scanner-dev.core-dev.aws.cere.io'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ }}
